#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void driveLeft1(long power)
{
	setMotorSpeed(rightMotor, power);
	setMotorSpeed(leftMotor, power / 2);
}

void driveRight1(long power)
{
	setMotorSpeed(rightMotor, power / 2);
	setMotorSpeed(leftMotor, power);
}

void drive(long power)
{
	setMotorSpeed(rightMotor, power);
	setMotorSpeed(leftMotor, power);
}

void turn90degreesRight()
{
	// snap right
	setMotorSpeed(leftMotor, 30);
	setMotorSpeed(rightMotor, -30);
	sleep(650);
}

void turn90degreesLeft()
{
	// snap left
	setMotorSpeed(leftMotor, -30);
	setMotorSpeed(rightMotor, 30);
	sleep(650);
}

void swingRight90D()
{
	// swing right
	setMotorSpeed(leftMotor, 50);
	setMotorSpeed(rightMotor, 30);
	sleep(1300);
}

void swingLeft90D()
{
	// swing right
	setMotorSpeed(leftMotor, 30);
	setMotorSpeed(rightMotor, 50);
	sleep(1300);
}

void forward1S()
{
	// go straight
	setMotorSpeed(leftMotor, 50);
	setMotorSpeed(rightMotor, 50);
	sleep(1250);
}

void avoidObstacle()
{
	setMotorSpeed(rightMotor, 0);
	setMotorSpeed(leftMotor, 0);
	sleep(500);
	swingRight90D();
	setMotorSpeed(rightMotor, 0);
	setMotorSpeed(leftMotor, 0);
	swingLeft90D();
	setMotorSpeed(rightMotor, 0);
	setMotorSpeed(leftMotor, 0);
	forward1S();
	setMotorSpeed(rightMotor, 0);
	setMotorSpeed(leftMotor, 0);
	swingLeft90D();
}

float generateThreshold()
{
	int n = 0;
	float threshold = 0;
	int countLight = 0;

	while(n < 2)
	{

		if(getButtonPress(buttonEnter) == 1)
		{
			sleep(1000);
			displayCenteredBigTextLine(n*2,"Light = %d", SensorValue(S1));
			countLight = countLight+SensorValue(S1);
			n=n+1;
		}

	}

	threshold = countLight/n;
	displayCenteredTextLine(5, "Average = %f",threshold);
	sleep(2000);
	return threshold;

}


task main()
{
	bool noObstacle = true;
	float threshold = generateThreshold();

	while(true)
	{
		// 25
		if(SensorValue(S3) < 30)
		{
			avoidObstacle();
		}

		while(SensorValue(S1) > 40 & noObstacle)
		{
			driveLeft1(50);
		}

		while(SensorValue(S1) < 40 & noObstacle)
		{
			driveRight1(50);
		}

	}

}
