#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will move your robot make a series of moves for different lengths of time.
  At the end of the program, all motors will shut down automatically and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                [Description]
    MotorC        	leftMotor           LEGO EV3 Motor	  Left side motor
    MotorB       	rightMotor          LEGO EV3 Motor	  Right side motor (reversed)
------------------------------------------------------------------------------------------------*/


void moveRobot(long nMotorRatio, long time, long power)
{
	setMotorSyncTime(leftMotor, rightMotor, nMotorRatio ,time ,power);
	sleep(time);

}

void square()
{
	moveRobot(0,1000,50);
	moveRobot(50,890,50);
	moveRobot(0,1000,50);
	moveRobot(50,890,50);
	moveRobot(0,1000,50);
	moveRobot(50,890,50);
	moveRobot(0,1000,50);
	moveRobot(50,890,50);
}



task main()
{
	//square();
	// go straight for 5 seconds, turn around and come back at half power
	moveRobot(0,5000,100);
	moveRobot(50,1780,50);
	moveRobot(0,10000,50);
}
