/* 
The code defines several functions, each of which controls the movement of the robot in a specific way: 
turning 90 degrees left or right, 
moving forward or in reverse for 1 second, 
or swinging left or right 90 degrees.
*/


#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, openLoop, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, openLoop, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will move your robot make a series of moves for different lengths of time.
  At the end of the program, all motors will shut down automatically and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                [Description]
    MotorC        	leftMotor           LEGO EV3 Motor	  Left side motor
    MotorB       	rightMotor          LEGO EV3 Motor	  Right side motor (reversed)
------------------------------------------------------------------------------------------------*/





void turn90degreesLeft()
{
	// snap left
	setMotorSpeed(leftMotor, -30);
	setMotorSpeed(rightMotor, 30);
	sleep(900);
}

void turn90degreesRight()
{
	// snap right
	setMotorSpeed(leftMotor, 30);
	setMotorSpeed(rightMotor, -30);
	sleep(900);
}

void forward1S()
{
	// go straight
	setMotorSpeed(leftMotor, 100);
	setMotorSpeed(rightMotor, 100);
	sleep(1000);
}

void swingRight90D()
{
	// swing right
	setMotorSpeed(leftMotor, 50);
	setMotorSpeed(rightMotor, 30);
	sleep(3000);
}

void swingLeft90D()
{
	// swing right
	setMotorSpeed(leftMotor, 30);
	setMotorSpeed(rightMotor, 50);
	sleep(3000);
}

void reverse1S()
{
	setMotorSpeed(leftMotor, -100);
	setMotorSpeed(rightMotor, -100);
	sleep(1000);
}



task main()
{
	//reverse1S();
	//swingRight90D();
	//forward1S();
	//turn90degreesLeft();
	//turn90degreesRight();
}
