/*
This code is designed to avoid a set map that has obstacles in the way
*/

#pragma config(Sensor, S3,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will move your robot make a series of moves for different lengths of time.
  At the end of the program, all motors will shut down automatically and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                [Description]
    MotorC        	leftMotor           LEGO EV3 Motor	  Left side motor
    MotorB       	rightMotor          LEGO EV3 Motor	  Right side motor (reversed)
------------------------------------------------------------------------------------------------*/





void moveRobot(long nMotorRatio, long power)
{
	setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 1000, power);
}

void turn90(long nMotorRatio, long power)
{
	// Sequence to turn 90 degrees
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
	sleep(1400);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
	setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 1000, power);
	sleep(1200);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
}


task main()
{
	SensorType[S4] = sensorEV3_Ultrasonic; // Initialize the ultrasonic Sensor
	int n = 0;

	while(n != 3) //  The map only has 3 obstacles and we are required to stop after the third
	{
		int distance = getUSDistance(S4);
		
		if(getUSDistance(S4) > 50) // If we are far from an object, continue driving
		{
			moveRobot(0,100);
		}

		if(getUSDistance(S4) < 50) // If we see an object, turn 90 degrees
		{
			turn90(-25,50);
			n = n+1; // Increment
		}
		
		if(getTouchValue(S3) == 1) // If we crash
		{
			moveRobot(0,-100);
		}
		
	}

}