#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will move your robot make a series of moves for different lengths of time.
  At the end of the program, all motors will shut down automatically and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                [Description]
    MotorC        	leftMotor           LEGO EV3 Motor	  Left side motor
    MotorB       	rightMotor          LEGO EV3 Motor	  Right side motor (reversed)
------------------------------------------------------------------------------------------------*/

void drive(long nMotorRatio, long dist, long power)
{
	setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, dist, power);
}

void turn90(long nMotorRatio, long power)
{
	setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 800, power);
}

task main()
{
	short randomNum = random(100);

	if (randomNum >= 50)
	{
		randomNum = -25;
	}
	else
	{
		randomNum = 25;
	}
	// 1000 aprox. 25cm
	// 9250 = 240cm
	short length = 2000;
	drive(0, length, 100);
	sleep(length * 2);
	turn90(randomNum,50);
	sleep(3000);
	drive(0, length, 100);
	sleep(length * 2);
	turn90(randomNum,50);
	sleep(3000);
	drive(0, length, 100);
	sleep(length * 2);
	turn90(randomNum,50);
	sleep(3000);
	drive(0, length, 100);
	sleep(length * 2);
	turn90(randomNum,50);
	sleep(3000);



}
